kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "main-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "main-service.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "main-service.fullname" . }}
  apiGroup: rbac.authorization.k8s.io