apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ template "main-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - primitives.atomix.io
  resources:
  - '*'
  resourceNames:
  - configurations
  - resources
  - streams
  - topology
  - metrics
  - events
  - device-models
  - main-service-log
  - monitor-service-log
  - tsn-service-log
  - gnmi-netconf-adapter-log
  - config-subsystem-log
  - topology-subsystem-log
  verbs:
  - '*'