apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tsn-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "tsn-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "tsn-service.fullname" . }}
      app: onos
      type: tsn
      resource: {{ template "tsn-service.fullname" . }}
      {{- include "tsn-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "tsn-service.fullname" . }}
        {{- include "tsn-service.selectorLabels" . | nindent 8 }}
        app: onos
        type: tsn
        resource: {{ template "tsn-service.fullname" . }}
        {{- include "tsn-service.selectorLabels" . | nindent 8 }}
      annotations:
        broker.atomix.io/inject: "true"
        raft.storage.atomix.io/inject: "true"
    spec:
      serviceAccountName: {{ template "tsn-service.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "tsn-service.imagename" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OIDC_SERVER_URL
              value: {{ .Values.openidc.issuer }}
            - name: SERVICE_NAME
              value: {{ template "tsn-service.fullname" . }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: grpc
              containerPort: 5150
          volumeMounts:
            - name: config
              mountPath: /etc/onos/config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- if .Values.debug }}
            capabilities:
              add:
                - SYS_PTRACE
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "tsn-service.fullname" . }}-config
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}