apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: configurations
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: resources
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: streams
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: topology
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: metrics
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: events
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: device-models
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Value
metadata:
  name: main-service-log
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: monitor-service-log
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: tsn-service-log
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: gnmi-netconf-adapter-log
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: config-subsystem-log
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: topology-subsystem-log
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "open-cnc.store.consensus.name" . }}
    {{- end }}
