apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: {{ template "monitor-service.fullname" . }}-test
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "monitor-service.store.consensus.name" . }}
    {{- end }}
