nameOverride: "gnmi-netconf-adapter"
fullnameOverride: "gnmi-netconf-adapter"

replicaCount: 1
annotations: {}

image:
  repository: onosproject/gnmi-netconf-adapter
  tag: v0.0.1
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

service:
  type: ClusterIP

ports:
  gnmi:
    secure: 10161
    insecure: 11161

nodeSelector: {}

tolerations: []

affinity: {}
